tokens:
  - token: ETHUSDT
    sources: chainlink
  - token: WSTETHUSDT
    sources: chainlink  
  - token: NSTETH
    sources: beaconchain
sender:
  mnemonic: ""
  path: /root/testnetV6/Operator1/config
imua:
  chainid: imuachaintestnet_233-8
  appName: imua
  grpc: 127.0.0.1:9090
  ws: !!str ws://127.0.0.1:26657/websocket
  rpc: !!str http://127.0.0.1:26657
debugger:
  grpc: !!str :50054  