sources:
  - chainlink
tokens:
  - ETHUSDT
  - WSTETHUSDT
  - USDCUSDT
sender:
  mnemonic: ""
  path: /root/testnetV6/node4/config
exocore:
  chainid: exocoretestnet_233-6
  appName: exocore
  rpc: 127.0.0.1:10003
  ws:
    addr: !!str ws://127.0.0.1:19997
    endpoint: /websocket
