tokens:
  - token: ETHUSDT
    sources: chainlink
  - token: WSTETHUSDT
    sources: chainlink  
  - token: NSTETH
    sources: beaconchain
sender:
  mnemonic: ""
  path: /root/testnetV6/node3/config
imua:
  chainid: imuachaintestnet_233-8
  appName: imua
  grpc: 127.0.0.1:10002
  ws: !!str ws://127.0.0.1:19998/websocket
  rpc: !!str http://127.0.0.1:19998
debugger:
  grpc: !!str :50053