tokens:
  - token: ETHUSDT
    sources: chainlink
  - token: WSTETHUSDT
    sources: chainlink  
  - token: NSTETH
    sources: beaconchain
sender:
  mnemonic: ""
  path: /root/tesstnetV6/node2/config
imua:
  chainid: imuachaintestnet_233-8
  appName: imua
  grpc: 127.0.0.1:10001
  ws: !!str ws://127.0.0.1:19999/websocket
  rpc: !!str http://127.0.0.1:19999
debugger:
  grpc: !!str :50052